from flask import Flask, render_template_string, request
import re

app = Flask(__name__)

HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CyberShield Security Scanner</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #0b1120;
            color: #e5e7eb;
            max-width: 850px;
            margin: 40px auto;
            padding: 20px;
        }
        h1 { color: #38bdf8; }
        .card {
            background: #172033;
            padding: 22px;
            border-radius: 12px;
            margin: 20px 0;
        }
        input, button {
            padding: 12px;
            border-radius: 6px;
            border: none;
            margin-top: 10px;
        }
        input { width: 90%; }
        button {
            background: #0284c7;
            color: white;
            cursor: pointer;
        }
        .good { color: #4ade80; }
        .warning { color: #fbbf24; }
        footer { color: #94a3b8; margin-top: 35px; }
    </style>
</head>
<body>
    <h1>🛡️ CyberShield</h1>
    <p>Beginner-friendly cybersecurity education and security checks.</p>

    <div class="card">
        <h2>Password Strength Checker</h2>
        <form method="POST">
            <input type="password" name="password"
                   placeholder="Enter a test password"
                   required minlength="1">
            <br>
            <button type="submit">Check Strength</button>
        </form>

        {% if result %}
            <h3 class="{{ level }}">{{ result }}</h3>
            <p>{{ advice }}</p>
        {% endif %}
    </div>

    <div class="card">
        <h2>Website Security Checklist</h2>
        <ul>
            <li>Use HTTPS for website traffic.</li>
            <li>Keep software and dependencies updated.</li>
            <li>Use multi-factor authentication.</li>
            <li>Set appropriate security headers.</li>
            <li>Back up important data regularly.</li>
        </ul>
    </div>

    <footer>
        Educational project. Do not enter real or reused passwords.
    </footer>
</body>
</html>
"""

@app.route("/", methods=["GET", "POST"])
def home():
    result = ""
    advice = ""
    level = ""

    if request.method == "POST":
        password = request.form.get("password", "")

        score = sum([
            len(password) >= 12,
            bool(re.search(r"[a-z]", password)),
            bool(re.search(r"[A-Z]", password)),
            bool(re.search(r"\d", password)),
            bool(re.search(r"[^a-zA-Z0-9]", password))
        ])

        if len(password) < 8:
            result = "Weak password"
            advice = "Use a longer password or passphrase."
            level = "warning"
        elif score >= 4 and len(password) >= 12:
            result = "Good basic complexity"
            advice = "Consider using a unique password generated by a password manager."
            level = "good"
        else:
            result = "Could be stronger"
            advice = "Consider a longer, unique passphrase and avoid predictable patterns."
            level = "warning"

    return render_template_string(
        HTML, result=result, advice=advice, level=level
    )

if __name__ == "__main__":
    app.run(debug=True)
